### ISSUE TITLE
Intermittent TreeIndex test failure

### ISSUE THREAD

**Issue by wvwwvwwv** [wvwwvwwv/scalable-concurrent-containers#161]
```
failures:

---- tests::correctness::treeindex_test::insert_remove_clear stdout ----
thread '<unnamed>' panicked at src/tree_index/leaf_node.rs:742:13:
assertion failed: unmarked
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:148:5
   3: scc::tree_index::leaf_node::LeafNode<K,V>::rollback
             at ./src/tree_index/leaf_node.rs:742:13
   4: scc::tree_index::node::Node<K,V>::rollback
             at ./src/tree_index/node.rs:343:38
   5: scc::tree_index::node::Node<K,V>::split_root
             at ./src/tree_index/node.rs:238:17
   6: scc::tree_index::TreeIndex<K,V>::insert
             at ./src/tree_index.rs:189:42
   7: scc::tests::correctness::treeindex_test::insert_remove_clear::{{closure}}
             at ./src/tests/correctness.rs:1924:41
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'tests::correctness::treeindex_test::insert_remove_clear' panicked at src/tests/correctness.rs:1948:27:
called `Result::unwrap()` on an `Err` value: Any { .. }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1102:23
   4: scc::tests::correctness::treeindex_test::insert_remove_clear
             at ./src/tests/correctness.rs:1948:13
   5: scc::tests::correctness::treeindex_test::insert_remove_clear::{{closure}}
             at ./src/tests/correctness.rs:1906:29
   6: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

https://github.com/wvwwvwwv/scalable-concurrent-containers/actions/runs/10935952056/job/30358899891?pr=160

**Comment by changgyoopark-db** [comment]
invalid debug assertion
