### ISSUE TITLE
TreeIndex test sporadic failure

### ISSUE THREAD

**Issue by wvwwvwwv** [wvwwvwwv/scalable-concurrent-containers#65]
---- tests::correctness::treeindex_test::remove stdout ----
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`: 2 1 2', src/tests/correctness.rs:522:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tests::correctness::treeindex_test::remove' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/tests/correctness.rs:528:27

**Comment by wvwwvwwv** [comment]
another occurrence.

thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `17`,
 right: `16`: 17 16 16', src/tests/correctness.rs:511:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by wvwwvwwv** [comment]
The latest change causes the issue to resurface.

thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `18`,
 right: `17`: 18 18 17', src/tests/correctness.rs:816:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tests::correctness::treeindex_test::remove' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/tests/correctness.rs:822:27
